import { CMSNavbar } from "@/app/components";
import Provider from "@/app/utils/Provider";
import "@/app/globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <CMSNavbar />
          {children}
        </Provider>
      </body>
    </html>
  );
}
